const player_2223 = [
    {
        first_name: 'Kepa',
        last_name: 'Arrizabalaga',
        position: 'Goalkeeper',
        role: 0,
        backnumber: 1,
        season: 2223,
    },
    {
        first_name: 'Marcus',
        last_name: 'Bettinelli',
        position: 'Goalkeeper',
        role: 0,
        backnumber: 13,
        season: 2223,
    },
    {
        first_name: 'Gabriel',
        last_name: 'Slonina',
        position: 'Goalkeeper',
        role: 0,
        backnumber: 36,
        season: 2223,
    },
    {
        first_name: 'Benoit',
        last_name: 'Badiashile',
        position: 'Centre-back',
        role: 1,
        backnumber: 4,
        season: 2223,
    },
    {
        first_name: '',
        last_name: 'Thiago Silva',
        position: 'Centre-back',
        role: 1,
        backnumber: 6,
        season: 2223,
    },
    {
        first_name: 'Trevoh',
        last_name: 'Chalobah',
        position: 'Centre-back',
        role: 1,
        backnumber: 14,
        season: 2223,
    },
    {
        first_name: 'Ben',
        last_name: 'Chilwell',
        position: 'Left-back / Wing-back',
        role: 1,
        backnumber: 21,
        season: 2223,
    },
    {
        first_name: 'Reece',
        last_name: 'James',
        position: 'Defender / Wing-back',
        role: 1,
        backnumber: 24,
        season: 2223,
    },
    {
        first_name: 'Mark',
        last_name: 'Cucurella',
        position: 'Defender / Wing-back',
        role: 1,
        backnumber: 32,
        season: 2223,
    },
    {
        first_name: 'Wesley',
        last_name: 'Fofana',
        position: 'Centre-back',
        role: 1,
        backnumber: 33,
        season: 2223,
    },
    {
        first_name: 'Kai',
        last_name: 'Havertz',
        position: 'Striker',
        role: 3,
        backnumber: 29,
        season: 2223,
    },
    {
        first_name: 'Romelu',
        last_name: 'Lukaku',
        position: 'Striker',
        role: 3,
        backnumber: 9,
        season: 2223,
    },
    ]
    
    export default player_2223;