const player_2425 = [
    {
        first_name: 'Robert',
        last_name: 'Sanchez',
        position: 'Goalkeeper',
        role: 1,
        backnumber: 1,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Filip',
        last_name: 'Jorgensen',
        position: 'Goalkeeper',
        role: 1,
        backnumber: 12,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Marcus',
        last_name: 'Bettinelli',
        position: 'Goalkeeper',
        role: 1,
        backnumber: 13,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Lucas',
        last_name: 'Bergstrom',
        position: 'Goalkeeper',
        role: 1,
        backnumber: 47,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Axel',
        last_name: 'Disasi',
        position: 'Centre-back',
        role: 2,
        backnumber: 2,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Marc',
        last_name: 'Cucurella',
        position: 'Defender / Wing-back',
        role: 2,
        backnumber: 3,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Tosin',
        last_name: 'Adarabioyo',
        position: 'Centre-back',
        role: 2,
        backnumber: 4,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Benoit',
        last_name: 'Badiashile',
        position: 'Centre-back',
        role: 2,
        backnumber: 5,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Levi',
        last_name: 'Colwill',
        position: 'Centre-back',
        role: 2,
        backnumber: 6,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Ben',
        last_name: 'Chilwell',
        position: 'Left-back / Wing-back',
        role: 2,
        backnumber: 21,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Reece',
        last_name: 'James',
        position: 'Defender / Wing-back',
        role: 2,
        backnumber: 24,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Malo',
        last_name: 'Gusto',
        position: 'Right-back',
        role: 2,
        backnumber: 27,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Wesley',
        last_name: 'Fofana',
        position: 'Centre-back',
        role: 2,
        backnumber: 29,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Renato',
        last_name: 'Veiga',
        position: 'Defender / Midfielder',
        role: 2,
        backnumber: 40,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Enzo',
        last_name: 'Fernandez',
        position: 'Midfielder',
        role: 3,
        backnumber: 8,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Carney',
        last_name: 'Chukwuemeka',
        position: 'Midfielder',
        role: 3,
        backnumber: 17,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Kiernan',
        last_name: 'Dewsbury-Hall',
        position: 'Midfielder',
        role: 3,
        backnumber: 22,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Moises',
        last_name: 'Caicedo',
        position: 'Midfielder',
        role: 3,
        backnumber: 25,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Cesare',
        last_name: 'Casadei',
        position: 'Midfielder',
        role: 3,
        backnumber: 31,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Omari',
        last_name: 'Kellyman',
        position: 'Midfielder',
        role: 3,
        backnumber: 37,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Romeo',
        last_name: 'Lavia',
        position: 'Midfielder',
        role: 3,
        backnumber: 45,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Pedro',
        last_name: 'Neto',
        position: 'Winger',
        role: 4,
        backnumber: 7,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Mykhailo',
        last_name: 'Mudryk',
        position: 'Winger',
        role: 4,
        backnumber: 10,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Noni',
        last_name: 'Madueke',
        position: 'Winger',
        role: 4,
        backnumber: 11,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: '',
        last_name: 'Joao Felix',
        position: 'Attacking Midfielder / Winger',
        role: 4,
        backnumber: 14,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Nicolas',
        last_name: 'Jackson',
        position: 'Striker',
        role: 4,
        backnumber: 15,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Christopher',
        last_name: 'Nkunku',
        position: 'Striker',
        role: 4,
        backnumber: 18,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Jadon',
        last_name: 'Sancho',
        position: 'Winger',
        role: 4,
        backnumber: 19,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Cole',
        last_name: 'Palmer',
        position: 'Attacking Midfielder / Winger',
        role: 4,
        backnumber: 20,
        season: 2425,
        isChelsea: 1,
    },
    {
        first_name: 'Marc',
        last_name: 'Guiu',
        position: 'Striker',
        role: 4,
        backnumber: 38,
        season: 2425,
        isChelsea: 1,
    },

]

export default player_2425;