const player_2425 = [
  {
    url_name: "robert-sanchez",
    first_name: "Robert",
    last_name: "Sanchez",
    position: "Goalkeeper",
    role: 0,
    backnumber: 1,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "filip-jorgensen",
    first_name: "Filip",
    last_name: "Jorgensen",
    position: "Goalkeeper",
    role: 0,
    backnumber: 12,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "marcus-bettinelli",
    first_name: "Marcus",
    last_name: "Bettinelli",
    position: "Goalkeeper",
    role: 0,
    backnumber: 13,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "lucas-bergstrom",
    first_name: "Lucas",
    last_name: "Bergstrom",
    position: "Goalkeeper",
    role: 0,
    backnumber: 47,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "axel-disasi",
    first_name: "Axel",
    last_name: "Disasi",
    position: "Centre-back",
    role: 1,
    backnumber: 2,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "marc-cucurella",
    first_name: "Marc",
    last_name: "Cucurella",
    position: "Defender / Wing-back",
    role: 1,
    backnumber: 3,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "tosin-adarabioyo",
    first_name: "Tosin",
    last_name: "Adarabioyo",
    position: "Centre-back",
    role: 1,
    backnumber: 4,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "benoit-badiashile",
    first_name: "Benoit",
    last_name: "Badiashile",
    position: "Centre-back",
    role: 1,
    backnumber: 5,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "levi-colwill",
    first_name: "Levi",
    last_name: "Colwill",
    position: "Centre-back",
    role: 1,
    backnumber: 6,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "ben-chilwell",
    first_name: "Ben",
    last_name: "Chilwell",
    position: "Left-back / Wing-back",
    role: 1,
    backnumber: 21,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "trevoh-chalobah",
    first_name: "Trevoh",
    last_name: "Chalobah",
    position: "Centre-back",
    role: 1,
    backnumber: 23,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "reece-james",
    first_name: "Reece",
    last_name: "James",
    position: "Defender / Wing-back",
    role: 1,
    backnumber: 24,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "malo-gusto",
    first_name: "Malo",
    last_name: "Gusto",
    position: "Right-back",
    role: 1,
    backnumber: 27,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "wesley-fofana",
    first_name: "Wesley",
    last_name: "Fofana",
    position: "Centre-back",
    role: 1,
    backnumber: 29,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "josh-acheampong",
    first_name: "Josh",
    last_name: "Acheampong",
    position: "Defender",
    role: 1,
    backnumber: 34,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "renato-veiga",
    first_name: "Renato",
    last_name: "Veiga",
    position: "Defender / Midfielder",
    role: 1,
    backnumber: 40,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "enzo-fernandez",
    first_name: "Enzo",
    last_name: "Fernandez",
    position: "Midfielder",
    role: 2,
    backnumber: 8,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "carney-chukwuemeka",
    first_name: "Carney",
    last_name: "Chukwuemeka",
    position: "Midfielder",
    role: 2,
    backnumber: 17,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "kiernan-dewsbury-hall",
    first_name: "Kiernan",
    last_name: "Dewsbury-Hall",
    position: "Midfielder",
    role: 2,
    backnumber: 22,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "moises-caicedo",
    first_name: "Moises",
    last_name: "Caicedo",
    position: "Midfielder",
    role: 2,
    backnumber: 25,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "cesare-casadei",
    first_name: "Cesare",
    last_name: "Casadei",
    position: "Midfielder",
    role: 2,
    backnumber: 31,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "omari-kellyman",
    first_name: "Omari",
    last_name: "Kellyman",
    position: "Midfielder",
    role: 2,
    backnumber: 37,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "romeo-lavia",
    first_name: "Romeo",
    last_name: "Lavia",
    position: "Midfielder",
    role: 2,
    backnumber: 45,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "pedro-neto",
    first_name: "Pedro",
    last_name: "Neto",
    position: "Winger",
    role: 3,
    backnumber: 7,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "mykhailo-mudryk",
    first_name: "Mykhailo",
    last_name: "Mudryk",
    position: "Winger",
    role: 3,
    backnumber: 10,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "noni-madueke",
    first_name: "Noni",
    last_name: "Madueke",
    position: "Winger",
    role: 3,
    backnumber: 11,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "joao-felix",
    first_name: "Joao",
    last_name: "Felix",
    position: "Attacking Midfielder / Winger",
    role: 3,
    backnumber: 14,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "nicolas-jackson",
    first_name: "Nicolas",
    last_name: "Jackson",
    position: "Striker",
    role: 3,
    backnumber: 15,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "christopher-nkunku",
    first_name: "Christopher",
    last_name: "Nkunku",
    position: "Striker",
    role: 3,
    backnumber: 18,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "jadon-sancho",
    first_name: "Jadon",
    last_name: "Sancho",
    position: "Winger",
    role: 3,
    backnumber: 19,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "cole-palmer",
    first_name: "Cole",
    last_name: "Palmer",
    position: "Attacking Midfielder / Winger",
    role: 3,
    backnumber: 20,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "tyrique-george",
    first_name: "Tyrique",
    last_name: "George",
    position: "Winger",
    role: 3,
    backnumber: 32,
    season: 2425,
    isChelsea: 1,
  },
  {
    url_name: "marc-guiu",
    first_name: "Marc",
    last_name: "Guiu",
    position: "Striker",
    role: 3,
    backnumber: 38,
    season: 2425,
    isChelsea: 1,
  },
];

export default player_2425;
